version: '3'
services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - 8080:80
    volumes:
      - D:/00_DATA/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_password
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    container_name: nextcloud_db
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=your_password
    volumes:
      - D:/00_DATA/nextcloud_db:/var/lib/mysql
    restart: unless-stopped
