version: '3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - D:/00_DATA/radarr:/config
      - D:/00_MEDIA_CENTER:/movies
      - D:/00_DOWNLOADS:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
